config/routes.rb
Cdr::Application.routes.draw do

  devise_for :users
  resources :calldetails

  resources :departments

  resources :companies

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/calldetail.rb
class Calldetail < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calldetails_controller.rb
class CalldetailsController < ApplicationController
  before_action :set_calldetail, only: [:show, :edit, :update, :destroy]

  # GET /calldetails
  # GET /calldetails.json
  def index
    @calldetails = Calldetail.all
  end

  # GET /calldetails/1
  # GET /calldetails/1.json
  def show
  end

  # GET /calldetails/new
  def new
    @calldetail = Calldetail.new
  end

  # GET /calldetails/1/edit
  def edit
  end

  # POST /calldetails
  # POST /calldetails.json
  def create
    @calldetail = Calldetail.new(calldetail_params)

    respond_to do |format|
      if @calldetail.save
        format.html { redirect_to @calldetail, notice: 'Calldetail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @calldetail }
      else
        format.html { render action: 'new' }
        format.json { render json: @calldetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calldetails/1
  # PATCH/PUT /calldetails/1.json
  def update
    respond_to do |format|
      if @calldetail.update(calldetail_params)
        format.html { redirect_to @calldetail, notice: 'Calldetail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @calldetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calldetails/1
  # DELETE /calldetails/1.json
  def destroy
    @calldetail.destroy
    respond_to do |format|
      format.html { redirect_to calldetails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calldetail
      @calldetail = Calldetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calldetail_params
      params.require(:calldetail).permit(:globalCallID_callId, :cdrRecordType, :origIpAddr, :callingPartyNumber, :destIpAddr, :originalCalledPartyNumber, :dateTimeConnect, :dateTimeDisconnect, :originalCalledPartyNumberPartition, :duration, :origDeviceName, :destDeviceName)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :email, :address, :phone, :create_date)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render action: 'show', status: :created, location: @department }
      else
        format.html { render action: 'new' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :create_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calldetails_helper.rb
module CalldetailsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calldetails/_form.html.erb
<%= form_for(@calldetail) do |f| %>
  <% if @calldetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calldetail.errors.count, "error") %> prohibited this calldetail from being saved:</h2>

      <ul>
      <% @calldetail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :globalCallID_callId %><br>
    <%= f.number_field :globalCallID_callId, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cdrRecordType %><br>
    <%= f.number_field :cdrRecordType, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :origIpAddr %><br>
    <%= f.number_field :origIpAddr, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :callingPartyNumber %><br>
    <%= f.text_field :callingPartyNumber, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :destIpAddr %><br>
    <%= f.number_field :destIpAddr, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :originalCalledPartyNumber %><br>
    <%= f.text_field :originalCalledPartyNumber, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :dateTimeConnect %><br>
    <%= f.number_field :dateTimeConnect, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :dateTimeDisconnect %><br>
    <%= f.number_field :dateTimeDisconnect, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :originalCalledPartyNumberPartition %><br>
    <%= f.text_field :originalCalledPartyNumberPartition, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :duration %><br>
    <%= f.number_field :duration, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :origDeviceName %><br>
    <%= f.text_field :origDeviceName, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :destDeviceName %><br>
    <%= f.text_field :destDeviceName, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/calldetails/edit.html.erb
<h1>Editing calldetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @calldetail, class:"btn btn-link" %> |
<%= link_to 'Back', calldetails_path, class:"btn btn-link" %>

app/views/calldetails/index.html.erb
<h1>Listing calldetails</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Globalcallid callid</th>
      <th>Cdrrecordtype</th>
      <th>Origipaddr</th>
      <th>Callingpartynumber</th>
      <th>Destipaddr</th>
      <th>Originalcalledpartynumber</th>
      <th>Datetimeconnect</th>
      <th>Datetimedisconnect</th>
      <th>Originalcalledpartynumberpartition</th>
      <th>Duration</th>
      <th>Origdevicename</th>
      <th>Destdevicename</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @calldetails.each do |calldetail| %>
      <tr>
        <td><%= calldetail.globalCallID_callId %></td>
        <td><%= calldetail.cdrRecordType %></td>
        <td><%= calldetail.origIpAddr %></td>
        <td><%= calldetail.callingPartyNumber %></td>
        <td><%= calldetail.destIpAddr %></td>
        <td><%= calldetail.originalCalledPartyNumber %></td>
        <td><%= calldetail.dateTimeConnect %></td>
        <td><%= calldetail.dateTimeDisconnect %></td>
        <td><%= calldetail.originalCalledPartyNumberPartition %></td>
        <td><%= calldetail.duration %></td>
        <td><%= calldetail.origDeviceName %></td>
        <td><%= calldetail.destDeviceName %></td>
        <td><%= link_to 'Show', calldetail, class:"btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_calldetail_path(calldetail), class:"btn btn-link" %></td>
        <td><%= link_to 'Destroy', calldetail, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calldetail', new_calldetail_path, class:"btn btn-link" %>

app/views/calldetails/new.html.erb
<h1>New calldetail</h1>

<%= render 'form' %>

<%= link_to 'Back', calldetails_path, class:"btn btn-link" %>

app/views/calldetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Globalcallid callid:</strong>
  <%= @calldetail.globalCallID_callId %>
</p>

<p>
  <strong>Cdrrecordtype:</strong>
  <%= @calldetail.cdrRecordType %>
</p>

<p>
  <strong>Origipaddr:</strong>
  <%= @calldetail.origIpAddr %>
</p>

<p>
  <strong>Callingpartynumber:</strong>
  <%= @calldetail.callingPartyNumber %>
</p>

<p>
  <strong>Destipaddr:</strong>
  <%= @calldetail.destIpAddr %>
</p>

<p>
  <strong>Originalcalledpartynumber:</strong>
  <%= @calldetail.originalCalledPartyNumber %>
</p>

<p>
  <strong>Datetimeconnect:</strong>
  <%= @calldetail.dateTimeConnect %>
</p>

<p>
  <strong>Datetimedisconnect:</strong>
  <%= @calldetail.dateTimeDisconnect %>
</p>

<p>
  <strong>Originalcalledpartynumberpartition:</strong>
  <%= @calldetail.originalCalledPartyNumberPartition %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @calldetail.duration %>
</p>

<p>
  <strong>Origdevicename:</strong>
  <%= @calldetail.origDeviceName %>
</p>

<p>
  <strong>Destdevicename:</strong>
  <%= @calldetail.destDeviceName %>
</p>

<%= link_to 'Edit', edit_calldetail_path(@calldetail), class:"btn btn-link" %> |
<%= link_to 'Back', calldetails_path, class:"btn btn-link" %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :create_date %><br>
    <%= f.date_select :create_date, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies demo</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Create date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.email %></td>
        <td><%= company.address %></td>
        <td><%= company.phone %></td>
        <td><%= company.create_date %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Create date:</strong>
  <%= @company.create_date %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :create_date %><br>
    <%= f.date_select :create_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Create date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.create_date %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Create date:</strong>
  <%= @department.create_date %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/layouts/_sidebar.html.erb
      <!-- Sidebar -->
            <!-- Sidebar -->
      <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
        <ul class="sidebar-nav" id="sidebar">   
          <li><a><span class="glyphicon glyphicon-dashboard"></span>Dashboard</a></li>
            <li><a href="<%= companies_path %>"><span class="sub_icon glyphicon glyphicon-home"></span>Companies</a></li>
          <li><a href="<%= companies_path %>"><span class="sub_icon glyphicon glyphicon-link"></span>Companies</a></li>
          <li> <a href="<%= departments_path %>"><span class="sub_icon glyphicon glyphicon-link"></span>Departments</a></li>
          <li><a href="<%= calldetails_path %>"><span class="sub_icon glyphicon glyphicon-link"></span>Calldetails</a></li>
          <li><a href="<%= calldetails_path %>"><span class="sub_icon glyphicon glyphicon-user"></span>Users</a></li>

        </ul>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cdr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "style", media: "all", "data-turbolinks-track" => true %>
   <%= stylesheet_link_tag    "sidebar", media: "all", "data-turbolinks-track" => true %>
  <%
=begin %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
<%
=end %>
 
   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body> 

<div id="wrapper" class="active">
      <%= render 'layouts/sidebar' %>         
      <!-- Page content -->
      <div id="page-content-wrapper">
        <!-- Keep all page content within the page-content inset div! -->
        <div class="page-content inset">
        <div class="row">
          <div class="col-md-12">
<p class="navbar-text pull-right">

<% if user_signed_in? %>
  Conectado como 
  <a href="#" class="navbar-link">Nombre Apellidos</a>
  <%= link_to "Editar perfil", edit_user_registration_path %>
   <%= link_to "logout", destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "Registro", new_user_registration_path %>
   <%= link_to "Login", new_user_session_path %>
<% end %>
</p>

          </div>
        </div>
         <div class="row">
           <div class="col-md-12">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

              <%= yield %>

            </div>
          </div>
        </div>
      </div>
      
    </div>

</body>
</html>

app/views/welcome/index.html.erb
 
              <p class="well lead">An Experiment using the sidebar template from startbootstrap.com which I integrated in my website (<a href="http://animeshmanglik.name">animeshmanglik.name</a>)</p>
              <p class="well lead">Click on the Menu to Toggle Sidebar . Hope you enjoy it!</p> 